package com.comitative.pic.parsers;

import com.comitative.pic.CodeReference;
import com.comitative.pic.ProfileEntry;
import org.jetbrains.annotations.NotNull;

import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

/**
 * Parser for the flat report format as generated by the Async Profiler.
 */
public class AsyncProfilerFlatParser implements ProfileParser {
    @Override
    public @NotNull Map<CodeReference, ProfileEntry> parseStream(InputStream inputStream) {
        return new HashMap<>();
    }
}
